In [1]:
import numpy as np
import pandas as pd

In [6]:
array1=np.array([12,13,14,15])
array1

array([12, 13, 14, 15])

In [7]:
array1[2]

14

In [8]:
array1[1:2]

array([13])

In [9]:
array1.ndim

1

In [10]:
type(array1)


numpy.ndarray

In [13]:
array2=np.array([[12,13,14],[15,16,17]])
array2
array2.ndim

2

In [14]:
array2[1]

array([15, 16, 17])

In [15]:
array2[1][0]

15

In [16]:
array2[1][1:3]

array([16, 17])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(20,40)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [21]:
np.arange(20,40,6)

array([20, 26, 32, 38])

In [22]:
np.arange(-20,40,5)

array([-20, -15, -10,  -5,   0,   5,  10,  15,  20,  25,  30,  35])

In [23]:
np.arange(40,20,6)

array([], dtype=int64)

In [24]:
np.linspace(12,34,16)

array([12.        , 13.46666667, 14.93333333, 16.4       , 17.86666667,
       19.33333333, 20.8       , 22.26666667, 23.73333333, 25.2       ,
       26.66666667, 28.13333333, 29.6       , 31.06666667, 32.53333333,
       34.        ])

In [26]:
demo1=pd.Series(np.arange(5))
demo1

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [28]:
demo2=pd.Series(np.arange(12,17))
demo2

0    12
1    13
2    14
3    15
4    16
dtype: int64

In [30]:
demo3=pd.DataFrame([demo1,demo2])
demo3

0   1   2   3   4
0   0   1   2   3   4
1  12  13  14  15  16

In [31]:
demo3.T

0   1
0  0  12
1  1  13
2  2  14
3  3  15
4  4  16

In [33]:
dummy={'Name':['Hari','Devi','Priya',np.nan],
       'Age':[22,23,np.nan,24],
       'Track':['ML','Cyber','CAD',np.nan]}
dummy

{'Name': ['Hari', 'Devi', 'Priya', nan],
 'Age': [22, 23, nan, 24],
 'Track': ['ML', 'Cyber', 'CAD', nan]}

In [34]:
df=pd.DataFrame(dummy)
df

Name   Age  Track
0   Hari  22.0     ML
1   Devi  23.0  Cyber
2  Priya   NaN    CAD
3    NaN  24.0    NaN

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    3 non-null      object 
 1   Age     3 non-null      float64
 2   Track   3 non-null      object 
dtypes: float64(1), object(2)
memory usage: 224.0+ bytes


In [37]:
df.isnull()

Name    Age  Track
0  False  False  False
1  False  False  False
2  False   True  False
3   True  False   True

In [38]:
df.isnull().sum()

Name     1
Age      1
Track    1
dtype: int64

In [39]:
df.loc[0:2,'Name':'Track']

Name   Age  Track
0   Hari  22.0     ML
1   Devi  23.0  Cyber
2  Priya   NaN    CAD

In [43]:
df.iloc[0:3,0:2]

Name   Age
0   Hari  22.0
1   Devi  23.0
2  Priya   NaN